apiVersion: v1
description: Dragoon Databases
icon: https://dragoons.io/assets/img/logo_vsmall.png
name: drgdb
version: 0.1.0
appVersion: 0.1.0
keywords:
- dragoons
- drg
- drg-database
- database
- db
sources:
- https://github.com/DragoonsBets/drgMsDBs
maintainers:
- name: pablog12
  email: pgarcia@dragoons.io
- name: orsiemilio
  email: eorsi@dragoons.io
- name: halbano
  email: halbano@dragoons.io
- name: gnardone
  email: gnardone@dragoons.io