apiVersion: v1
description: Dragoon Databases
icon: https://dragoons.io/assets/img/logo_vsmall.png
name: drgdb
version: 0.1.0
appVersion: 0.1.0
keywords:
- dragoons
- drg
- drg-database
- database
- db
sources:
- https://github.com/DragoonsBets/drgMsDBs
maintainers:
name: drgdb
  email: pgarcia@dragoons.io
name: drgdb
  email: eorsi@dragoons.io
name: drgdb
  email: halbano@dragoons.io
name: drgdb
  email: gnardone@dragoons.io