# Default values for drgMsDBs.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

bffweb-postgres:
  postgresqlUsername: drgbffweb
  postgresqlDatabase: drgBffWeb

user-postgres:
  postgresqlUsername: drgmsuser
  postgresqlDatabase: drgMsUser