# Default values for drgMsDBs.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

bffweb-postgres:
  postgresqlUsername: drgbffweb
  postgresqlDatabase: drgBffWeb
  pgHbaConfiguration: |-
    local all all trust
    host all all localhost trust
    host all all drgbffweb trust

user-postgres:
  postgresqlUsername: drgmsuser
  postgresqlDatabase: drgMsUser
  pgHbaConfiguration: |-
    local all all trust
    host all all localhost trust
    host all all drgmsuser trust